#!/usr/bin/env bash

BUILDROOT=`pwd`
SVNPATH="http://c0decafe.de/svn/"
REPNAME=codename_loki
PKGNAME=loki
WORKDIR=$BUILDROOT/loki-build-`date +%F_%H-%M`
NONRELEASE=`cat<<-EOF
	build.sh
	misc
	test
	pkg_scripts
	modules/module_test.py
	modules/module_snmp.py
	modules/module_snmp.glade
	modules/module_802_1X.py
	modules/module_802_1X.glade
EOF`

echo "**************************"
echo "**** creating workdir ****"
echo "**************************"
mkdir $WORKDIR

echo "***********************"
echo "**** exporting svn ****"
echo "***********************"
cd $WORKDIR
svn export $SVNPATH/$REPNAME/trunk

echo "**************************************"
echo -n "**** getting version ... "
VERSION=`grep "VERSION =" trunk/src/loki.py | cut -d\" -f2`
echo "$VERSION ****"
echo "**************************************"

echo "***********************************"
echo "**** removing non-release data ****"
echo "***********************************"
for i in $NONRELEASE; do
	echo "deleting $i"
	rm -rf trunk/$i
done

echo "*************************"
echo "**** moving in place ****"
echo "*************************"
mv trunk $PKGNAME-$VERSION

echo "***************************"
echo "**** creating tar file ****"
echo "***************************"
tar -cvzf ${PKGNAME}_${VERSION}.orig.tar.gz $PKGNAME-$VERSION

echo "********************************"
echo "**** building pkg for amd64 ****"
echo "********************************"
rpmbuild -ba $PKGNAME-$VERSION/loki.spec

#~ echo "*******************************"
#~ echo "**** building pkg for i386 ****"
#~ echo "*******************************"
#~ sudo chroot /chroot32 /usr/bin/sudo -u user /bin/sh -c "cd $WORKDIR/$PKGNAME-$VERSION && /usr/bin/debuild -us -uc"

