#!/usr/bin/env bash

BUILDROOT=/home/user
SVNPATH="svn+ssh://svn/home/greif/svn/"
REPNAME=codename_loki
PKGNAME=loki
WORKDIR=$BUILDROOT/build-loki-`date +%F_%H-%M`
NONRELEASE=`cat<<-EOF
	build.sh
	misc
	test
	modules/module_test.py
	modules/module_snmp.py
	modules/module_snmp.glade
EOF`

echo "creating workdir"
mkdir $WORKDIR

echo "exporting svn"
cd $WORKDIR
svn export $SVNPATH/$REPNAME/trunk

echo -n "getting version ... "
VERSION=`grep "VERSION =" trunk/src/loki.py | cut -d\" -f2`
echo $VERSION

echo "removing non-release data"
for i in $NONRELEASE; do
	echo "deleting $i"
	rm -rf trunk/$i
done

echo "moving in place"
mv trunk $PKGNAME-$VERSION

echo "creating tar file"
tar -cvzf ${PKGNAME}_${VERSION}.orig.tar.gz $PKGNAME-$VERSION

echo "configuring build root"
cd $PKGNAME-$VERSION
aclocal
autoconf
automake --add-missing --copy
./configure

echo "building pkg"
debuild -us -uc

